export interface Flashcard {
  id: string;
  question: string;
  answer: string;
  options: string[]; // Array of choices including the correct answer
}

export interface ChatMessage {
  role: 'user' | 'model';
  text: string;
  timestamp: number;
}

export interface StudySession {
  id: string;
  fileName: string;
  title: string; // Content-based title generated by AI
  fileType: string;
  fileData: string; // Base64
  summary: string;
  flashcards: Flashcard[];
  chatHistory: ChatMessage[];
  createdAt: number;
}

export enum AppView {
  UPLOAD = 'UPLOAD',
  DASHBOARD = 'DASHBOARD',
}

export enum TabView {
  SUMMARY = 'SUMMARY',
  FLASHCARDS = 'FLASHCARDS',
}